### ISSUE TITLE
HowTo configure add-on

### ISSUE THREAD

**Issue by gianfrdp** [fl4p/batmon-ha#94]
I installed add-on on HA supervised (Intel NUC).
From documentation it's not clear how to configure it.
Do I have to add something into configuration.yaml? If yes, can I have a complete example, please?

I tried to follow config.yaml file as example:
```
options:
  devices:
    - address: C8:47:8C:EC:BF:F3
      type: jk
      alias: JK_2A20S20P
  mqtt_user: ""
  mqtt_password: ""
  mqtt_broker: "192.168.2.32"
```
but HA doesn't accept it:
`Integration error: options - Integration 'options' not found.`

I saw there is a file options.json in /usr/share/hassio/addons/data/2af0a32d_batmon
but it is overwritten if I try to customize it

**Comment by fl4p** [comment]
```
devices:
  - address: C8:47:8C:EC:BF:F3
    type: jk
    alias: JK_2A20S20P
mqtt_user: ""
mqtt_password: ""
mqtt_broker: "192.168.2.32"
```
